travis:
  secure:
    BINSTAR_TOKEN: P0ntHX1RdP+JWfE76GbRbGwBrl2HNrGCy0rdFBflb30vEdP48c3qwHoV1PgfVR4UyNfc2ewRKhQLWqEGbxvoAew7BCk23ARrki+vcdqYeokDvEUkHwOaQdDxGFkVu+XOZU6C82NspqjxmChb/laHciVRZHB46/U7UXFf/b54bOXC9plN8tFxNf0EAzmhfzPoAK+V8dImxquiKYETtK7Tb8Yp8FJPi7urx9JaeL2Pn6/XPtJ+Rbsv+Wq+jCg6UF2ZcRWRS12u/ZHutpPhHTbkJzg22udqjJecOm1XhNDWNoA1fgZ4/X6BaEujKSKDiwYYardw5mIfSnd6GCLoK54p2CLUPQKDgz7NXgbwKn136CO5k/793yg+gQKNYZCIHrLuB0mhUqsL0pCcgFYEI2hZtF48oo/909PzcRNYybSZx5pE2STgFCg0ELxIfbGBQxw6rbAfS5xzi5/Dgmpxu7jL+kRCs5O42ifLXg8wPeb4H5K/SMcXW5BLZOJ10bCZmjUqpI5DceRk62emevNDe8JcQP9BFr41M/behFpj1qKr6PEpzXqyi6JbY9+fq1XLJ6ERx9NjLPeXpz2n0x1aJ1q/ogoIRNy/sTnBi5/IkdtPVRMD+9zokRTHSfV8pu1B78bjma1l2qxF0Bv9ikOdvmOd2E6fetHHP3Eb7phyb919lyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
