travis:
  secure:
    BINSTAR_TOKEN: NE5CkRWVqPgqIeO0ycN0ggSaAwIPiN/UlIKaXbUkw2bCKi3FmZ/PkvCkfXLkDMky68vZG6U9Q1ybN3/Kd3p/8aUEmJc9nWPIdyyTvF89B7VZhl6PM1rctu2i3ZosFAxxpueVemi7E/PVvcoGTbPov47Xwy6X9jh2EU5KHIGGXIzy1bLQwg2GVgkpYMWtFW+47fQpt+4hnHS3VJBAQMUBtyJxfIhOfU9xcpKbtbugiwpDrTTEnMX6anmGBFJxg82IWmw1cU/aSk25i71QWe5j6njwWA35YsAFZMTf2gSAS8/d2sCW3ghmGVrygSKHHt47eeG+1GbyhO0CMV34ekeu3RMhYyDETz0XcGhO2sKU19IjcsUf5cfOWlHLbW2uXfZxVTRDv0/dIpNYcQGjxrymNLMn9+Ls6LMbAIOO+Tx9QaxHOkNqgT9qQEI6TLetyymOrX3B+wEk9zuQMQ1FCyP5DS9naviG74yvzWch8fJTO4bCX5vNVTBn0Ee5gqLSv37yrGDuoxFMN+UT5627+15/FnKQ5Ez+yeR0+hhmx895Rh0CEfqiOvJ+xszppcxgtmRVXvzB2YNuMDxxAAzSWOabsJk/tdyEwCFqhOVBs8txBA6YJYS72Gs8NcI73BvCXb4nv2dFvPrXO9QrZcSyCKVhlVM+DKhwV+jpeF1OWdDLD1k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
